### ISSUE TITLE
Add your argument cuando la pregunta está más abajo de la página

### ISSUE THREAD

**Issue by LdonosoC** [joserobleda/decidder-new#10]
Hay una respuesta ya creada el final de la página. Bajo la barra de desplazamiento y pulso en "add your argument" y el modal que se abre se pierde.. no se visualiza..

**Comment by pdelmoral** [comment]
Esto es un problema con el modal, ya que esta hidden y según su posicion se puede quedar 'fuera'. Esto hay que verlo, lo trataremos como tarea yo creo. 

Como te comento esta verde, pero no esta demás tener todos estos problemas apuntados, yo he encontrado mas de este tipo, cuando termine el día si no los soluciono los dejo apuntados aquí tb.

**Comment by LdonosoC** [comment]
Ya ya si ya se que esta verde pero si vamos apuntando todo, como tu dices,
pues mejor

**Comment by pdelmoral** [comment]
Me parece perfect :+1:
