### ISSUE TITLE
Cada user solo una respuesta por pregunta

### ISSUE THREAD

**Issue by pdelmoral** [joserobleda/decidder-new#11]

**Comment by LdonosoC** [comment]
Esto lo vamos a dejar comentado???

**Comment by LdonosoC** [comment]
> Esto lo vamos a dejar comentado???

@pdelmoral lo vamos a dejar o no?

**Comment by pdelmoral** [comment]
Según hablamos no lo vamos a dejar comentado. Quieres que lo deje ya para que solo se pueda responder una vez?

**Comment by LdonosoC** [comment]
si no te importa, si por favor

**Comment by pdelmoral** [comment]
Ya debería funcionar @LdonosoC

**Comment by LdonosoC** [comment]
He visto que cuando das una respuestas, el botón de "writte a response" ya no sale, sin embargo el de "add your argument" si sale y éste tampoco debería salir no? si solo vamos a dejar una respuesta por usuario.....

**Comment by pdelmoral** [comment]
Tienes toda la razon. Lo hice despues y se me ha pasado. Lo hago para que no salga
