### ISSUE TITLE
Repasar versión movil

### ISSUE THREAD

**Issue by pdelmoral** [joserobleda/decidder-new#12]

**Comment by LdonosoC** [comment]
No se visualiza ningún icono en la versión movil.. ni el de writte a response, ni el de edit your questions.. ninguno. Lo que se ven son rectángulos vacios

**Comment by pdelmoral** [comment]
He abierto otro bug solo con esto, ya que al ser genérico tendríamos que estar abriendo y cerrando cunado se hagan cosas nuevas.
