### ISSUE TITLE
Cambiar diseño formato numero respuesta '#num_respuesta'

### ISSUE THREAD

**Issue by pdelmoral** [joserobleda/decidder-new#13]

**Comment by joserobleda** [comment]
a ver que tal la idea... se pueden poner otros colores

**Comment by pdelmoral** [comment]
Me gusta la idea.

Señor diseñador propongo color de fondo #CDFFC5 (o similar jeje)

**Comment by joserobleda** [comment]
> Señor diseñador propongo color de fondo #CDFFC5 (o similar jeje)

Creo que en tu pantalla este color debe verse muuuy diferente

**Comment by pdelmoral** [comment]
jajajaja o tengo muy mal gusto...

La idea era un verde muuuy clarito, se te ve asi?

**Comment by joserobleda** [comment]
veo un verde "radioactivo" XD

**Comment by pdelmoral** [comment]
jaja creo que se confirma el mal gusto entonces, no se estuve probando colores hasta q di con ese que me gusto, en mi defensa diré q a Evelyn tb le gusto.

Puedes proponer un verde que te encaje? Mi idea iba por verde clarito como te comento, no se que te parecerá...

**Comment by joserobleda** [comment]
si si, lo miro

**Comment by joserobleda** [comment]
nada, he probado un montón de verdes y no me encaja ninguno, he puesto otro color grisáceo a ver que tal.

**Comment by pdelmoral** [comment]
llámame loco pero lo veo blanco, rgba(255,255,255,0,8)

**Comment by joserobleda** [comment]
al tener el 0.8 se convierte en un gris muy claro... pero vamos, si.

**Comment by pdelmoral** [comment]
jeje esq mi ojo no llega a tanto, como sois los diseñadores... xD

El 3 de abril de 2013 13:51, joserobleda notifications@github.comescribió:

> al tener el 0.8 se convierte en un gris muy claro... pero vamos, si.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Babelbite/decidder-new/issues/13#issuecomment-15832311
> .

## 

http://www.dokify.net/
*Pablo del Moral · *Software Engineer
pdelmoral@dokify.net

## 914 816 417

Síguenos en ...
 Twitter https://twitter.com/dokify   Google+ http://gplus.to/dokify
