### ISSUE TITLE
Diseño de la ventana y situacion de mas informción

### ISSUE THREAD

**Issue by janayama** [joserobleda/decidder-new#19]

**Comment by joserobleda** [comment]
el diseño está cambiado, ahora ya es cosa de @janayama el js que hace que el efecto sea mas normal

**Comment by LdonosoC** [comment]
Ya he visto como sale y mola, pero hay una cosa que no me convence y es que si tu pregunta tiene tags, sale primero el contexto, luego más info y luego los tags y parece que estas últimas están ahí descolgadas y no se sabe muy bien que son. No sé como podríamos hacer para que se entienda que son, para que sepan que son las posibles respuestas que pueden utilizar o algo así....

**Comment by janayama** [comment]
Las posibles respuestas de las que hablan se va a quitar para el modo no edición.
