### ISSUE TITLE
Formatear fechas

### ISSUE THREAD

**Issue by janayama** [joserobleda/decidder-new#20]

**Comment by pdelmoral** [comment]
¿ que idea tenemos exactamente sobre esto?

**Comment by joserobleda** [comment]
hace que se vean con un formato normal, lo todo el churro que sale ahora

**Comment by pdelmoral** [comment]
ok de momento entonces con el mismo tipo de letra y diseño? Simplemente lo pongo para que salga con formato normal q es lo que entiendo de la issue.

**Comment by joserobleda** [comment]
esa es la idea...

**Comment by joserobleda** [comment]
he visto que las fechas que pone la app son siempre la fecha de visualización .. no la fecha de cada cosa... me pasa solo a mi?

**Comment by pdelmoral** [comment]
nop, me he dado cuenta esta mañana, lo tengo que mirar a ver, porque creo
qeu sera de loq ue hice yo...

2013/5/6 joserobleda notifications@github.com
