### ISSUE TITLE
mantener la url del usuario cuando haga login

### ISSUE THREAD

**Issue by joserobleda** [joserobleda/decidder-new#26]
que cuando hagas login si estabas viendo una pregunta, vuelvas a esa pregunta.

**Comment by LdonosoC** [comment]
He ido a dar una respuesta desde una url, he pulsado en "write a response", introduzco mi respuesta,  pulso send, me ha redirigdo a hacer login y, una vez que he hecho login, me ha vuelto a redirigir a la pregunta pero tengo que volver a introducir la respuesta... no me la guarda y es un poco coñazo...

**Comment by joserobleda** [comment]
ya, pero es otra issue, y ya la puso @pdelmoral  -> #44

**Comment by LdonosoC** [comment]
Cuando el usuario que accede es un usuario ya registrado, redirige a la respuesta sin problemas, pero si es un usuario que no ha accedido nunca y que tiene que confirmar su mail, no funciona correctamente, ya que una vez que ha introducido el mail, no le redirige a la pregunta que estaba visualizando
