### ISSUE TITLE
Ventana "response to users questions"

### ISSUE THREAD

**Issue by LdonosoC** [joserobleda/decidder-new#29]
Creo una nueva pregunta...
Accedo con otro usuario y solicito más información y cuando accedo de nuevo con el owner y pulso en response to users questions.. en algunas ocasiones se abre una ventana que dice "abort".
Además, cuando consigo que me aparezcan la ventana con las preguntas de más información, algunas veces cuando pulso sobre una de ellas para contestar, no se carga la ventana. Por debajo de la ventana donde está el listado de solicitudes de los usuarios, se ve que aparece una nueva ventana, que es donde tendría que introducir la respuesta, pero vuelve a desaparecer.

**Comment by janayama** [comment]
Lo que he probado funciona. No he conseguido reproducirlo.

**Comment by LdonosoC** [comment]
He intentado reproducirlo y no me sale, en caso de que me vuelta a salir ya te digo
