### ISSUE TITLE
Respuestas de solicitudes de más información

### ISSUE THREAD

**Issue by LdonosoC** [joserobleda/decidder-new#30]
Tengo varias solicitudes de más información en una pregunta y aunque conteste a todas las solicitudes. en el botón de "request to users questions" me sigue apareciendo el nº de solicitudes que tenia y si me vuelven a realizar otra solicitud no me llega ningún  mail.

**Comment by janayama** [comment]
> en el botón de "request to users questions" me sigue apareciendo el nº de solicitudes

Si no hay solicitudes por contestar no aparece el boton. Y el numero de solicitudes representa las que quedan por contestar.

> y si me vuelven a realizar otra solicitud no me llega ningún mail

Solo envia uno por question, para no recrgar las pruebas.

**Comment by LdonosoC** [comment]
Tengo que responder a una solicitud de más información y en el botón de "response to users question" no aparece el nº de solicitudes que me quedan por contestas, de hecho no aparece ningún nº
