### ISSUE TITLE
Eliminar una respuestas tuya

### ISSUE THREAD

**Issue by LdonosoC** [joserobleda/decidder-new#31]
He accedido con un usuario a una pregunta que no es mía, para dar una respuesta.
Después de dar de alta la respuesta, he intentado eliminarla y no me aparece el icono de la papelera

**Comment by LdonosoC** [comment]
No sé si lo he entendido mal.. ¿no se supone que cada usuario puede borrar sus respuestas? o ¿solo el owner puede borrar las respuestas? ya no tengo muy claro como hablamos que sería

**Comment by joserobleda** [comment]
deberían poder el que lanza la pregunta y el mismo que pone la respuesta, los 2

**Comment by LdonosoC** [comment]
Pues el owner es el único que puede borrar respuestas, ahora mismo
