### ISSUE TITLE
No autorizar a deccider en twitter

### ISSUE THREAD

**Issue by LdonosoC** [joserobleda/decidder-new#33]
Introduzco una nueva pregunta y pulso en go!.
Me redirige directamente a twitter... y no pulso en cancelar, porque no quiero autorizar a la aplicación y después pulso en volver a deccider y, en vez de volver, me indica No found

**Comment by joserobleda** [comment]
donde haces click exactamente?
donde estas (url) cuando ves ese "not found"?

**Comment by joserobleda** [comment]
ahora mismo te indica simplemente que ha ocurrido un error... creo que está bien como está
