### ISSUE TITLE
Contestar antes de inciar sesión

### ISSUE THREAD

**Issue by LdonosoC** [joserobleda/decidder-new#35]
Accedo a una pregunta mediante un link. Pulso en "write a response", introduzco la respuesta y pulso en send. Me redirije a twitter para que haga login y después me redirige a la home, en vez de a la pregunta en la que estaba con la respuesta que había introducido...

**Comment by LdonosoC** [comment]
Lo mismo ocurre si estoy visualizando una pregunta e Inicio Sesión, en vez redirije a la pregunta que estaba visualizando, me redirije a la home.

**Comment by joserobleda** [comment]
duplicada: 

https://github.com/Babelbite/decidder-new/issues/26
