### ISSUE TITLE
Mostar el número de visualizaciones de una pregunta

### ISSUE THREAD

**Issue by joserobleda** [joserobleda/decidder-new#40]

**Comment by pdelmoral** [comment]
Para probar que se suman bien las visitas hay que tener en cuenta que se comprueban las cookies de nuestro navegador, es decir, que por cambiar de usuario no va a sumar una visita.

**Comment by LdonosoC** [comment]
@pdelmoral en la última reunión hablamos de una prueba que querías que hiciera y te dije que me lo apuntaras por aquí, pero se te ha debido de olvidar ¿te cuerdas?

**Comment by pdelmoral** [comment]
Si perdona se me ha pasado.

La idea es que el comportamiento es distinto si tienes la cookie en tu
navegador o no. Esta cookie es única para las diferentes questions, es
decir que la primera vez que entres a una question (sin cookie) el código
que se va a ejecutar es distinto a la primera vez que entres a una question
con la cookie. Evidentemente esto es transparente para el usuario, pero hay
que probar las diferentes opciones.

Por otra la parte esta puesto para que la cookie caduque a las 24h, y seria
bueno probar que esto esta funcionando correctamente. Si no sabes donde
puedes ver las cookies me dices, o si tienes cualquier duda.
