### ISSUE TITLE
Formatear email

### ISSUE THREAD

**Issue by joserobleda** [joserobleda/decidder-new#41]

**Comment by janayama** [comment]
Pongo unas cuantas capturas a ver que os parecen, y que os gusta mas...

Esta es la actual:

![test1](https://f.cloud.github.com/assets/473509/629016/8fa842ee-d118-11e2-92e1-85aad062e303.png)

Sin los grises y con bordes:

![test2](https://f.cloud.github.com/assets/473509/629018/96e213b4-d118-11e2-994f-fb89416ec675.png)

Sin el gris de la cabecera que a @LdonosoC no le molaba:

![test3](https://f.cloud.github.com/assets/473509/629019/9e3c71cc-d118-11e2-873d-601c180353e3.png)

Sin estilo, a la izquieda:

![test4](https://f.cloud.github.com/assets/473509/629020/b0a49c40-d118-11e2-85e1-99a2400aa5c8.png)

Sin estilo pero con linea sepando e titulo:

![test5](https://f.cloud.github.com/assets/473509/629023/bd304bb2-d118-11e2-8036-40f12fc3337e.png)

BONUS TRACK @LdonosoC rosita style:

![test6](https://f.cloud.github.com/assets/473509/629026/d23d3010-d118-11e2-913b-491129517e3f.png)

**Comment by joserobleda** [comment]
A mi me gusta "Sin los grises y con bordes:" pero habría que alinear el texto a la imagen. Y quizás un borde un poco mas gris, para que no llame tanto la atención

**Comment by janayama** [comment]
He hecho los cambios que has recomendado, a mi personalmente me gusta.

![captura de pantalla de 2013-06-09 22 07 35](https://f.cloud.github.com/assets/473509/629326/538054d2-d140-11e2-86f9-f1c03f403abc.png)

**Comment by joserobleda** [comment]
Solo un detalle más, mismo padding vertical que horizontal en el párrafo
