### ISSUE TITLE
Se eliminan las respuestas predefinidas

### ISSUE THREAD

**Issue by LdonosoC** [joserobleda/decidder-new#55]
Creo una pregunta con respuestas predefinidas, pero en cuanto editas la pregunta, se borran las respuestas predefinidas...

**Comment by LdonosoC** [comment]
He visto que se borran, porque cuando editas la pregunta, no aparecen las respuestas predefinidas que ya pusé y al guardar, pues se borran.

**Comment by pdelmoral** [comment]
@joserobleda he solucionado que se vean las predefined responses pero rehaciendo como estaba hehco basicamente (por eso no hago push), y despues viendo los cambios que hiciste en este commit 8de4ab02efe7e0eb52781c4395371c86dd18e563 voy a ver si lo soluciono manteniendo como lo pusiste...

**Comment by joserobleda** [comment]
pufff, no recuerdo bien como lo hice, pero vamos, hazlo como veas, mientras que quede bien...
