### ISSUE TITLE
Duplicidad de preguntas al crear la primera

### ISSUE THREAD

**Issue by LdonosoC** [joserobleda/decidder-new#56]
Un usuario que no tiene ninguna pregunta creada, introduce una pregunta, pulsa go y le redirige a la pantalla de editar pregunta.
Luego accede a las preguntas del usuario y tiene creada dos en vez de una... una solo con el titulo de la pregunta y otra con la pregunta y la información editada...

Luego después he creado otra y ha funcionado correctamente... debe ocurrir solo cuando creas la primera

**Comment by joserobleda** [comment]
cada vez que entras en una pregunta se duplica.. creo..

**Comment by LdonosoC** [comment]
a mi eso no me.ha pasado....

**Comment by joserobleda** [comment]
No soy capaz de reproducir el error.. tienes mas info?

**Comment by LdonosoC** [comment]
Pues no sé te digo lo que he hecho porque me ha vuelto a pasa.
- He borrado todas las colecciones
- Me he logado
- He puesto mi mail
- He introducido una una nueva pregunta
- Me ha redirigido a editar la pregunta y he introducido el contexto
- He accedido a mis preguntas y me han aparecido dos preguntas, una con contexto y otra si contexto

**Comment by joserobleda** [comment]
Esto solo me pasa en el server, en mi local no hay forma.. @janayama @pdelmoral os pasa a vosotros?

**Comment by janayama** [comment]
A mi solo me sale una...

**Comment by pdelmoral** [comment]
+1

**Comment by pdelmoral** [comment]
Creo que he podido encontrr el motivo de que se duplicaran, lo he modificado en este commit 663e6526e58368ffc3ea382cd0790bd782202793, aunque no he terminado la funcionalidad de numero de visitas por este error ya no debería reproducirse este bug.
