### ISSUE TITLE
Link update sin que se haya modificado nada

### ISSUE THREAD

**Issue by LdonosoC** [joserobleda/decidder-new#59]
Pulso en `Edit your question`, no modifico nada y pulso en `Save`.
Si otro usuario está visualizando la pregunta, le aparece `This question has been updated. Click here to refresh!`, cuando en verdad no se ha modificado nada.
¿ podríamos hacer que si no se modifica nada no se muestre este menaje?
Es que claro si pulsas sobre el link no se va a actualizar nada...

**Comment by joserobleda** [comment]
@janayama te la asigno por que estuviste haciendo lo del onChange si no recuerdo mal
