### ISSUE TITLE
No se visualiza ningún icono en la versión movil

### ISSUE THREAD

**Issue by pdelmoral** [joserobleda/decidder-new#60]
No se visualiza ningún icono en la versión movil.. ni el de writte a response, ni el de edit your questions.. ninguno. Lo que se ven son rectángulos vacios

**Comment by pdelmoral** [comment]
Creo que esto lo hablamos y era porque @LdonosoC tenia la version del navegador desactualizado, a mi se me muestran correctamente los iconos. Si confirmas que era eso cierra la issue.

**Comment by LdonosoC** [comment]
Cierto.. he vuelto a mirar y se ve pefectamente. Puedes cerrar.
