### ISSUE TITLE
Añadir a una pregunta respuestas predefinidas

### ISSUE THREAD

**Issue by LdonosoC** [joserobleda/decidder-new#62]
Creo una nueva pregunta y no configuro preguntas predeterminadas.. 
Doy una respuesta a esta pregunta.
Después modifico la pregunta y le configuro respuestas predefinidas
Accedo con otro usuario y al dar una respuesta no visualizo las respuestas predefinidas, sin embargo si borro la primera respuesta que dí, entonces ya si me salen las respuestas predefinidas.

**Comment by pdelmoral** [comment]
He seguido los pasos y desde el principio me salen las respuestas predefinidas, vuelve a probar, y me dices si te sigue pasando.

De todos modos lo que hablamos es incluir las respuestas que se han dado en el select para pdoer elegirlas también. Me pongo con esto que igualmente lo tengo que hacer.
