### ISSUE TITLE
Refresh cuando no hay actualizaciones

### ISSUE THREAD

**Issue by LdonosoC** [joserobleda/decidder-new#64]
Dos usuarios diferentes están visualizando una pregunta.
Uno de ellos cambia, y visualiza otra pregunta diferente y todos los cambios que se realizan en cualquier de las dos preguntas, lo visualiza el otro usuario sin tener porque, ya que no están visualizando la misma pregunta.. 

Hace cosas raras.. si queréis os lo enseño mejor mañana......

**Comment by joserobleda** [comment]
le tendré que pedir a @pdelmoral y a @janayama que me ayuden, por que estoy viendo el código y todo parece estar bien, sin embargo si que me pasa lo que dices...

**Comment by pdelmoral** [comment]
Creo que esto es lo que estuvimos hablando el Lunes pasado y ya estaba 'encarrilado'.
