### ISSUE TITLE
Login en twitter en versión movil

### ISSUE THREAD

**Issue by LdonosoC** [joserobleda/decidder-new#65]
Intento hacer login en twitter desde el movil y me dice internal server error

**Comment by LdonosoC** [comment]
No funciona cuando al hacer login selecciono la app de twitter en vez de el navegador.

**Comment by joserobleda** [comment]
yo no consigo que me falle.. igual es de la versión de android, te sigue pasando esto?

**Comment by pdelmoral** [comment]
A mi em funciona correctamente también
