### ISSUE TITLE
Select respuestas predefinidas

### ISSUE THREAD

**Issue by LdonosoC** [joserobleda/decidder-new#70]
Creo una pregunta con respuestas predefinidas y cuando voy a dar una respuesta, no me aparece para seleccionar las respuestas predefinidas....
Recuerdo que esto ya pasó y ahora se ha vuelto a reproducir

**Comment by LdonosoC** [comment]
De hecho no se están guardando las respuestas predefinidas...

**Comment by pdelmoral** [comment]
Creo que esto se ha solucionado de nuevo, a mi me funciona bien...Cierro y si se reproduce reabrimos.
