### ISSUE TITLE
Usuarios que visualizan preguntas eliminadas

### ISSUE THREAD

**Issue by LdonosoC** [joserobleda/decidder-new#72]
Elimino una pregunta y a los usuarios que la esten visualizando no se lo comunicamos de ninguna manera, hasta que refresca la página. En ese momento se indica:

Uuuups! We found and error!
Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters

No sería mejor poner que la pregunta ha sido eliminada?

**Comment by joserobleda** [comment]
Un 404 not found.
