### ISSUE TITLE
Decidder en IE

### ISSUE THREAD

**Issue by LdonosoC** [joserobleda/decidder-new#77]
Así se ve deccider en IE

![image](https://f.cloud.github.com/assets/1584017/758451/c3a32f5c-e732-11e2-88a3-c6b38a8db351.png)

**Comment by joserobleda** [comment]
Que versión?

**Comment by LdonosoC** [comment]
El pantallazo es del 7, pero he mirado el 8 y se ve parecido...

**Comment by joserobleda** [comment]
yo creo que no vamos a dar soporte a esos browser, mínimo 9, 10 y 11

**Comment by LdonosoC** [comment]
Como veais, a mi no me parece mal!!!

2013/7/8 joserobleda notifications@github.com

**Comment by janayama** [comment]
A mi me parece lo suyo...

2013/7/8 Lioba notifications@github.com

> Como veais, a mi no me parece mal!!!
> 
> 2013/7/8 joserobleda notifications@github.com
> 
> > yo creo que no vamos a dar soporte a esos browser, mínimo 9, 10 y 11
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/Babelbite/decidder-new/issues/77#issuecomment-20587667>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Babelbite/decidder-new/issues/77#issuecomment-20588033
> .

## 

http://www.dokify.net/*
*
_Javier Anaya_\* · *Software Engineer

## janaya@dokify.net

Síguenos en ...
 Twitter http://twitter.com/dokify  Google+ http://gplus.to/dokify

**Comment by pdelmoral** [comment]
y algún mensaje informativo de que actualice versión o cambie de navegador al menos??

**Comment by joserobleda** [comment]
Si, algo hay que poner.
