### ISSUE TITLE
Alta de respuestas sin seleccionar tags

### ISSUE THREAD

**Issue by LdonosoC** [joserobleda/decidder-new#8]
Cuando voy a dar de alta una nueva "response", y la pregunta tiene tags de respuestas cerradas, en el desplegable además de poner las respuestas cerradas que ha introducido el owner, también aparece el texto de "edita la pregunta si quieres delimitar las respuestas", además de que el texto no es correcto porque debería ser algo así como "Elige una de estas respuestas", si no seleccionas ninguna de las otras respuestas cerradas, te crea una nueva entrada con el titulo de "edita la pregunta si quieres delimitar las respuesta". No debería dejar dar de alta una response, si no has seleccionado algún tags ¿o me equivoco?

**Comment by pdelmoral** [comment]
Esto es porque realmente sale ese tag como una opcion al principio y tendrías que elimnarlo al crear las respuestas predefinidas,ya que realmente estas poniendolo como opcion de respuesta. podemos ver como hacemos, pero si lo he entendido bien es lo que te comento.

Lo vemos.

**Comment by LdonosoC** [comment]
Cierto, es lo que comentas, pero yo creo que no debería ser un tags más si
no un texto explicativo sin más.

2013/3/31 pdelmoral notifications@github.com

> Esto es porque realmente sale ese tag como una opcion al principio y
> tendrías que elimnarlo al crear las respuestas predefinidas,ya que
> realmente estas poniendolo como opcion de respuesta. podemos ver como
> hacemos, pero si lo he entendido bien es lo que te comento.
> 
> Lo vemos.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Babelbite/decidder-new/issues/8#issuecomment-15690461
> .

## 

 http://www.dokify.net/
*Lioba Donoso Carbajo · *Testing and support
ldonoso@dokify.net

## 914 816 417 *· *628 718 070

Síguenos en ...
 Twitter https://twitter.com/dokify   Google+ http://gplus.to/dokify

**Comment by pdelmoral** [comment]
Esta claro, esta todo bastante verde, lo vamos viendo.

**Comment by pdelmoral** [comment]
De momento lo cierro eliminando el texto de respuesta libre, si queremos cambiar este comportamiento lo hablamos. 

En modo editar si que se indica que hay que poner predefined repsonses
